const dict = [
    {common: 'а', omuan: 'a',},
    {common: 'б', omuan: 'b',},
    {common: 'в', omuan: 'v',},
    {common: 'г', omuan: 'g',},
    {common: 'д', omuan: 'd',},
    {common: 'е', omuan: 'e',},
    {common: 'ё', omuan: '@',},
    {common: 'ж', omuan: 'j',},
    {common: 'з', omuan: 'z',},
    {common: 'и', omuan: 'i',},
    {common: 'й', omuan: 'q',},
    {common: 'к', omuan: 'k',},
    {common: 'л', omuan: 'l',},
    {common: 'м', omuan: 'm',},
    {common: 'н', omuan: 'n',},
    {common: 'о', omuan: 'o',},
    {common: 'п', omuan: 'p',},
    {common: 'р', omuan: 'r',},
    {common: 'с', omuan: 's',},
    {common: 'т', omuan: 't',},
    {common: 'у', omuan: 'u',},
    {common: 'ф', omuan: 'f',},
    {common: 'х', omuan: 'h',},
    {common: 'ц', omuan: 'c',},
    {common: 'ч', omuan: '4',},
    {common: 'ш', omuan: 'w',},
    {common: 'щ', omuan: 'x',},
    {common: 'ь', omuan: '`',},
    {common: 'ъ', omuan: '6',},
    {common: 'ы', omuan: 'y',},
    {common: 'э', omuan: '3',},
    {common: 'ю', omuan: '0',},
    {common: 'я', omuan: '9',},
]

module.exports = dict
